Allow Extending classes to override printResultSet, switch to HSQLDB (#63)
To allow other plugins to extend this plugin and be able to format the
output differently, we needed to change the printResultSet() from private
to protected. Also removed the printing of the rows affected to the
output file as this "corrupts" the output.

* cleanup, added unit tests, fixed default outputDelimiter, fixed java.lang.NoSuchMethodError: 'org.apache.commons.lang3.Range org.apache.commons.lang3.Range.of(java.lang.Comparable, java.lang.Comparable)'.

* Fixed outputDelimeter parameter default value handling

* Fixed Web UI master branch merge conflict resolve

* Optimized unit test performance and added additional information to test failures

* Changed Axion to HSQLDB and updated each test to use its database


Closes #26 
---------
Co-authored-by: George McCone <georgemccone@yahoo.com>
Co-authored-by: Timo Vuorijarvi <tim.vuorijarvi@gmail.com>